# Generated by Django 5.1.4 on 2024-12-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='account_manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
