# Generated by Django 5.1.4 on 2024-12-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_trainingrequest_account_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
