# Generated by Django 5.1.4 on 2024-12-18 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_trainingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
