# Generated by Django 5.1.4 on 2024-12-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('dashboards', '0006_trainingrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resources', models.URLField(blank=True, max_length=1024, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__role_name': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('employees', models.ManyToManyField(blank=True, limit_choices_to={'role__role_name': 'Employee'}, related_name='enrolled_courses', to='authentication.user')),
            ],
        ),
    ]
