# Generated by Django 5.1.4 on 2024-12-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_rename_courses_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='employees',
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='course_duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='employee_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of employees involved'),
            preserve_default=False,
        ),
    ]
