# Generated by Django 5.1.4 on 2024-12-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_course_employees_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='resources',
        ),
    ]
