# Generated by Django 5.1.4 on 2024-12-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_rename_resources_module_resource_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='resource_link',
            new_name='youtube_link',
        ),
    ]
