# Generated by Django 5.1.4 on 2025-01-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('dashboards', '0019_modulecompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecourseprogress',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='authentication.user'),
        ),
    ]
